In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso, Ridge,LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split



%matplotlib inline

In [29]:
names = ['appliances','kitch_temp', 'kitch_hum', 'palor_temp', 'palor_hum', 'laundry_temp',\
                   'laundry_hum','office_temp','office_hum', 'bathroom_temp', 'bathroom_hum','outside_temp','outside_hum',\
                   'ironing_temp','ironing_hum','teenageroom_temp', 'teenageroom_hum', 'parentroom_temp', 'parentroom_hum',\
                   'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed','Visibility', 'Tdewpoint', 'rv1', 'rv2' ]

In [52]:
energy_df = pd.read_csv('C:/Users/KOGI RAAMP/Downloads/energydata_complete.csv', index_col=None)
energy_df.columns=['date', 'appliances', 'lights', 'kitch_temp', 'kitch_hum', 'palor_temp', 'palor_hum', 'laundry_temp',\
                   'laundry_hum','office_temp','office_hum', 'bathroom_temp', 'bathroom_hum','outside_temp','outside_hum',\
                   'ironing_temp','ironing_hum','teenageroom_temp', 'teenageroom_hum', 'parentroom_temp', 'parentroom_hum',\
                   'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed','Visibility', 'Tdewpoint', 'rv1', 'rv2' ]
energy_df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [34]:
scaler = MinMaxScaler()
energy_df1 =energy_df.drop(columns=['date', 'lights'])

normalised_df = pd.DataFrame(scaler.fit_transform(energy_df1), columns=names)

In [37]:
train = normalised_df.drop(columns=['appliances'])
x_train, x_test, y_train, y_test = train_test_split(train, normalised_df['appliances'],
test_size=0.3, random_state=42)

In [19]:
normalised_df.head()

,kitch_temp,kitch_hum,palor_temp,palor_hum,laundry_temp,laundry_hum,office_temp,office_hum,bathroom_temp,bathroom_hum,...,parentroom_temp,parentroom_hum,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [40]:
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)
predicted_values = linear_model.predict(x_test)
r2_score = e(y_test, predicted_values)

In [43]:
mea = mean_absolute_error(y_test, predicted_values)

print (mea)

0.05013362397742954

In [44]:
rss = np.sum(np.square(y_test - predicted_values))
print(rss)

45.34762967266377

In [59]:
ridge = Ridge(alpha=0.4)
ridge.fit(x_train, y_train)
ridge_pred =ridge.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, ridge_pred))
print(rmse)

0.08753385704628003

In [55]:
lasso = Lasso(alpha=0.001)
lasso.fit(x_train, y_train)
lasso_pred =lasso.predict(x_test)

In [48]:
def get_weights(model, feature, col_name):
    weights = pd.Series(model.coef_, feature.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df


linear_model_weights = get_weights_df(linear_model, x_train, 'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso, x_train, 'Lasso_weight')

In [50]:
print(linear_model_weights)

            Features  Linear_Model_Weight
0          palor_hum            -0.456698
1              T_out            -0.321860
2         palor_temp            -0.236178
3    parentroom_temp            -0.189941
4    teenageroom_hum            -0.157595
5             RH_out            -0.077671
6        ironing_hum            -0.044614
7     parentroom_hum            -0.039800
8      bathroom_temp            -0.015657
9         kitch_temp            -0.003281
10               rv1             0.000770
11               rv2             0.000770
12       Press_mm_hg             0.006839
13      ironing_temp             0.010319
14        Visibility             0.012307
15      bathroom_hum             0.016006
16        office_hum             0.026386
17       office_temp             0.028981
18         Windspeed             0.029183
19       outside_hum             0.038049
20       laundry_hum             0.096048
21  teenageroom_temp             0.101995
22         Tdewpoint             0.117758
23      outside_temp             0.236425
24      laundry_temp             0.290627
25         kitch_hum             0.553547

In [54]:
print(lasso_weights_df)

            Features  Lasso_weight
0             RH_out     -0.049557
1    teenageroom_hum     -0.000110
2         kitch_temp      0.000000
3          Tdewpoint      0.000000
4         Visibility      0.000000
5        Press_mm_hg     -0.000000
6              T_out      0.000000
7     parentroom_hum     -0.000000
8    parentroom_temp     -0.000000
9   teenageroom_temp      0.000000
10       ironing_hum     -0.000000
11               rv1     -0.000000
12      ironing_temp     -0.000000
13      outside_temp      0.000000
14      bathroom_hum      0.000000
15     bathroom_temp     -0.000000
16        office_hum      0.000000
17       office_temp     -0.000000
18       laundry_hum      0.000000
19      laundry_temp      0.000000
20         palor_hum     -0.000000
21        palor_temp      0.000000
22       outside_hum     -0.000000
23               rv2     -0.000000
24         Windspeed      0.002912
25         kitch_hum      0.017880

In [57]:
rmse = np.sqrt(mean_squared_error(y_test, lasso_pred))
print(rmse)

0.09358170467245137

In [58]:
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
print(rmse)

0.0875144494766171